# https://docs.docker.com/compose/compose-file/
version: "3.9"
services:
  ubuntu:
    image: "ubuntu:latest"
    user: "root" # --user
    privileged: true # --privileged
    stdin_open: true # --interactive
    tty: true        # --tty
    ports: # --publish
      - "22:22"
    links: # --link
      - redis
#    depends_on:
#      - redis
  redis:
    image: "redis:alpine"